services:

  backend:
    build: ./app
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - chromadb
      - embedding-service
    restart: unless-stopped
    env_file:
      - ./.env_deploy

  embedding-service:
    build: ./embedding-service
    container_name: embedding-service
    ports:
      - "8005:8000"
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: unless-stopped

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chromadb
    ports:
      - "8003:8000"   # expose Chroma REST API at host:8003
    environment:
      - IS_PERSISTENT=TRUE     # enables persistence on disk
      - ALLOW_RESET=TRUE       # allows wiping/reset via API (dev only)
    volumes:
      - ./chroma:/data  # mount local folder into container
    restart: unless-stopped